services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    env_file:
      -  stack.env
    volumes:
      - /opt/mc-data:/data
    restart: unless-stopped
